
server:
  port: 8687


spring:
  datasource:
    username: bpmn.v.1.0
    password: HeZh3LWthBXkEEFt
    url: jdbc:mysql://150.158.96.29:3306/bpmn.v.1.0?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 60
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
      minimum-idle: 10
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl